### ISSUE TITLE
Error when using with webhook

### ISSUE THREAD

**Issue by danpoltawski** [lukefx/hubot-telegram#10]
Not sure if this is some environment problem since it seems such an 'obvious' error, but when I use with the webhook I get lots of:

```
TypeError: Cannot read property 'length' of undefined
  at /home/danp/bot/node_modules/hubot-telegram/src/telegram.coffee:153:17, <js>:189:36
  at callbacks (/home/danp/bot/node_modules/hubot/node_modules/express/lib/router/index.js:164:37)
  at param (/home/danp/bot/node_modules/hubot/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/danp/bot/node_modules/hubot/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/home/danp/bot/node_modules/hubot/node_modules/express/lib/router/index.js:173:5)
  at Object.router (/home/danp/bot/node_modules/hubot/node_modules/express/lib/router/index.js:33:10)
  at next (/home/danp/bot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.multipart [as handle] (/home/danp/bot/node_modules/hubot/node_modules/connect-multiparty/index.js:42:27)
  at next (/home/danp/bot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.urlencodedParser [as handle] (/home/danp/bot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:69:27)
  at next (/home/danp/bot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at /home/danp/bot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:107:5
  at IncomingMessage.onEnd (/home/danp/bot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
  at IncomingMessage.g (events.js:180:16)
  at IncomingMessage.EventEmitter.emit (events.js:92:17)
  at _stream_readable.js:920:16
  at process._tickCallback (node.js:415:13)
```

My node version:
```
node -v
v0.10.26
```

**Comment by arcturial** [comment]
This could possible be related to the content type the message is being passed with, I will do some local testing to see if I can replicate it.

**Comment by arcturial** [comment]
Ah nevermind, see you already found the issue.

**Comment by arcturial** [comment]
Did you fix solve the problem? mind creating a PR so I can merge it into the master branch?

**Comment by danpoltawski** [comment]
Yeah works with this. Will do - (was just hacking around so didn't create pull request)

**Comment by danpoltawski** [comment]
Oops, did I close this accidentally - sorry about that and thanks for fixing it.
