### ISSUE TITLE
Error: Bad Request: text is empty

### ISSUE THREAD

**Issue by rubybrowncoat** [lukefx/hubot-telegram#12]
Upon receiving any message ~~since 0.0.5 (I think)~~ on all versions: 

```
ERROR Error: Error: Bad Request: text is empty
  at Function.TelegramBot.error (node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:26:15)
  at Request._callback (node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:47:88)
  at Request.self.callback (node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:198:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:1057:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:1003:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:442:13)
```

**Comment by arcturial** [comment]
I am not experiencing this problem, do you perhaps have any custom heroku scripts running? The `text is empty` error usually happens when using `sendMessage` with an empty "text" parameter. The `getUpdates` call does not validate any `text` parameters.

**Comment by rubybrowncoat** [comment]
I'm not running on heroku. I'll try disabling some scripts and see what happens.

**Comment by arcturial** [comment]
sorry I meant hubot, not heroku XD

**Comment by rubybrowncoat** [comment]
Seem like it happens when the bot is trying to answer a command. I have as many errors as I have command in the getUpdates queue waiting to be processed.

**Comment by rubybrowncoat** [comment]
It fixed itself, somehow.

**Comment by arcturial** [comment]
You can add some debug on line 79 of telegram.coffee:

``` nodejs
    send: (envelope, strings...) ->
        self = @
        console.log(strings.join())
        @api.invoke 'sendMessage', { chat_id: envelope.room, text: strings.join() }, (err, message) =>
```

If that is populated but you receive the error, it means its somehow being lost in the adapter. If the output is empty, it is possibly a bad hubot script not specifying the message string correctly...possibly some script using `.hear` and trying to respond to every message. I haven't been able to replicate it on my instance.

**Comment by rubybrowncoat** [comment]
It isn't happening anymore. I just removed hubot-telegram's directory and reinstalled via npm. I will investigate further if it ever appears again. For now, I'll just close this.
