### ISSUE TITLE
Gateway Problem

### ISSUE THREAD

**Issue by filipre** [lukefx/hubot-telegram#26]
I'm pretty sure that this is not the adapter's fault but I would like to know if someone has similar problems:

```
[Sun Oct 11 2015 21:01:19 GMT+0200 (CEST)] ERROR Error: HTTP status 502 returned.
  at Function.TelegramBot.error (/home/rene/Development/hubot/node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:26:15)
  at Request._callback (/home/rene/Development/hubot/node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:48:62)
  at Request.self.callback (/home/rene/Development/hubot/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:198:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/home/rene/Development/hubot/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:1063:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/home/rene/Development/hubot/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:1009:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
```

I have this problem on my local machine as well as on my remote server. I also noticed that this occures multiple times. 

Any ideas how to solve this?

**Comment by arcturial** [comment]
I believe this happens when the Telegram servers are having issues. I found a couple of reports from August where people were complaining about the Telegram servers, it seems to have sort itself. Is it still happening today?

**Comment by filipre** [comment]
I see. The only thing to do is to wait then, I guess. 

>Is it still happening today?
It happened multiple times last week according to the server logs. Now it works again.
