### ISSUE TITLE
error on help command

### ISSUE THREAD

**Issue by elopio** [lukefx/hubot-telegram#41]
When I send the text "help" to my bot, the log shows:

2016-03-18T22:21:56.138903+00:00 app[web.1]: [Fri Mar 18 2016 22:21:56 GMT+0000 (UTC)] INFO Receiving message_id: 74
2016-03-18T22:21:56.552791+00:00 app[web.1]: [Fri Mar 18 2016 22:21:56 GMT+0000 (UTC)] ERROR Error: [Error]: Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 1042
2016-03-18T22:21:56.552805+00:00 app[web.1]:   at Function.TelegramBot.error (/app/node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:26:15)
2016-03-18T22:21:56.552806+00:00 app[web.1]:   at Request._callback (/app/node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:47:66)
2016-03-18T22:21:56.552807+00:00 app[web.1]:   at Request.self.callback (/app/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:199:22)
2016-03-18T22:21:56.552808+00:00 app[web.1]:   at Request.emit (events.js:98:17)
2016-03-18T22:21:56.552809+00:00 app[web.1]:   at Request.<anonymous> (/app/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:1036:10)
2016-03-18T22:21:56.552810+00:00 app[web.1]:   at Request.emit (events.js:117:20)
2016-03-18T22:21:56.552810+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:963:12)
2016-03-18T22:21:56.552811+00:00 app[web.1]:   at IncomingMessage.emit (events.js:117:20)
2016-03-18T22:21:56.552812+00:00 app[web.1]:   at _stream_readable.js:944:16
2016-03-18T22:21:56.552813+00:00 app[web.1]:   at process._tickCallback (node.js:458:13)
2016-03-18T22:21:56.552814+00:00 app[web.1]: 

I'm not sure if it's a problem in hubot, the telegram plugin or heroku. But as the error starts pointing to telegram I decided to start here. I'm new to this, so please let me know if I can provide more information.

**Comment by arcturial** [comment]
Hi

Try running the bot with "debug" on so that we can see the actual message the bot is receiving.

`export HUBOT_LOG_LEVEL="debug"`

**Comment by elopio** [comment]
Thanks for the reply. I set the variable in heroku and it started working. I removed it and it kept working.  ¯\_(ツ)_/¯ 
I'll close this, and keep an eye in case it starts happening again.
