### ISSUE TITLE
ERROR TypeError: Cannot read property 'message_id' of undefined

### ISSUE THREAD

**Issue by ishankhare07** [lukefx/hubot-telegram#46]
This happens when i try to call my bot using `@` syntax in a group
while it works fine for direct chat with bot

eg. `mybot help` -> works great in direct chat with the bot
`@mybot_username help` -> sucks in group chat

```
ERROR TypeError: Cannot read property 'message_id' of undefined
2016-04-05T21:35:09.531315+00:00 app[web.1]:   at Telegram.handleUpdate (/app/node_modules/hubot-telegram/src/telegram.coffee:176:28, <js>:217:64)
2016-04-05T21:35:09.531316+00:00 app[web.1]:   at Function.<anonymous> (/app/node_modules/hubot-telegram/src/telegram.coffee:251:29, <js>:288:36)
2016-04-05T21:35:09.531317+00:00 app[web.1]:   at Request._callback (/app/node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:51:12)
2016-04-05T21:35:09.531318+00:00 app[web.1]:   at Request.self.callback (/app/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:200:22)
2016-04-05T21:35:09.531319+00:00 app[web.1]:   at Request.emit (events.js:98:17)
2016-04-05T21:35:09.531320+00:00 app[web.1]:   at Request.<anonymous> (/app/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:1041:10)
2016-04-05T21:35:09.531320+00:00 app[web.1]:   at Request.emit (events.js:117:20)
2016-04-05T21:35:09.531321+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:968:12)
2016-04-05T21:35:09.531322+00:00 app[web.1]:   at IncomingMessage.emit (events.js:117:20)
2016-04-05T21:35:09.531323+00:00 app[web.1]:   at _stream_readable.js:944:16
2016-04-05T21:35:09.531324+00:00 app[web.1]:   at process._tickCallback (node.js:458:13)
```

**Comment by arcturial** [comment]
Does your bot use webhooks to receive updates or do you poll?

**Comment by ishankhare07** [comment]
I've only setup the `TELEGRAM_TOKEN` and not any other things

**Comment by arcturial** [comment]
What version of the bot are you running currently?

**Comment by arcturial** [comment]
Hey, the latest master version has some more debug in to debug incoming messages. Can you please give it a try and let me know what output you get? Also, are you using an inline bot?

**Comment by ishankhare07** [comment]
@arcturial will do that and let you know very soon

**Comment by arcturial** [comment]
Have you managed to replicate the issue with the latest debug additions active?

**Comment by rvrangel** [comment]
I was having the same problem with 0.1.0, but upgrading to master seems to have fixed it for me. Perhaps release a new version?

**Comment by iroes** [comment]
Maybe it has to do with a message update by telegram user after being sent. The telegram API responds with a JSON object that the adapter doesn't know how to answer (the object update.message is undefined in this case, then message_id doesn't exist either).

**Comment by EarlyEgg** [comment]
FYI, i had a similar problem.
`ERROR TypeError: Cannot read property 'hasOwnProperty' of undefined`
It turned out that msg.reply caused this and msg.send works fine.$

**Comment by lukefx** [comment]
#50 This branch should fix your issue, can I ask you to test it out? 
thx @ishankhare07

**Comment by lukefx** [comment]
As said, #50 should fix this issue. I will close this thread...hoping not have to re-open it 😃
