### ISSUE TITLE
Proxy issues

### ISSUE THREAD

**Issue by dtaytson** [lukefx/hubot-telegram#66]
I'm using hubot under a proxy and i'm receiving polling conflicts.
When I set interval > 6000 works but is a too high value... 

[Sat Jun 30 2018 18:15:45 GMT-0300 (-03)] ERROR TypeError: Cannot read property 'length' of null
    at Telegram.apiSend (/home/bot_test/bot_test/node_modules/hubot-telegram/src/telegram.coffee:122:51)
    at Telegram.send (/home/bot_test/bot_test/node_modules/hubot-telegram/src/telegram.coffee:147:6)
    at /home/bot_test/bot_test/node_modules/hubot/src/response.coffee:82:7
    at allDone (/home/bot_test/bot_test/node_modules/hubot/src/middleware.coffee:44:37)
    at /home/bot_test/bot_test/node_modules/async/lib/async.js:274:13
    at Object.async.eachSeries (/home/bot_test/bot_test/node_modules/async/lib/async.js:142:20)
    at Object.async.reduce (/home/bot_test/bot_test/node_modules/async/lib/async.js:268:15)
    at /home/bot_test/bot_test/node_modules/hubot/src/middleware.coffee:49:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[Sat Jun 30 2018 18:15:52 GMT-0300 (-03)] ERROR Error: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at Function.TelegramBot.error (/home/bot_test/bot_test/node_modules/telegrambot/lib/telegrambot.js:33:15)
    at Request._callback (/home/bot_test/bot_test/node_modules/telegrambot/lib/telegrambot.js:54:66)
    at Request.self.callback (/home/bot_test/bot_test/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bot_test/bot_test/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/bot_test/bot_test/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[Sat Jun 30 2018 18:15:57 GMT-0300 (-03)] ERROR Error: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at Function.TelegramBot.error (/home/bot_test/bot_test/node_modules/telegrambot/lib/telegrambot.js:33:15)
    at Request._callback (/home/bot_test/bot_test/node_modules/telegrambot/lib/telegrambot.js:54:66)
    at Request.self.callback (/home/bot_test/bot_test/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bot_test/bot_test/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/bot_test/bot_test/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[Sat Jun 30 2018 18:15:58 GMT-0300 (-03)] ERROR Error: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at Function.TelegramBot.error (/home/bot_test/bot_test/node_modules/telegrambot/lib/telegrambot.js:33:15)
    at Request._callback (/home/bot_test/bot_test/node_modules/telegrambot/lib/telegrambot.js:54:66)
    at Request.self.callback (/home/bot_test/bot_test/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bot_test/bot_test/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/bot_test/bot_test/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[Sat Jun 30 2018 18:16:02 GMT-0300 (-03)] ERROR Error: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at Function.TelegramBot.error (/home/bot_test/bot_test/node_modules/telegrambot/lib/telegrambot.js:33:15)
    at Request._callback (/home/bot_test/bot_test/node_modules/telegrambot/lib/telegrambot.js:54:66)
    at Request.self.callback (/home/bot_test/bot_test/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bot_test/bot_test/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/bot_test/bot_test/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by brandly** [comment]
i'm seeing both of these errors while running on heroku
