### ISSUE TITLE
Error seeking help

### ISSUE THREAD

**Issue by okada8** [lukefx/hubot-telegram#73]
I started like this：
"TELEGRAM_TOKEN=xxx:xxx TELEGRAM_INTERVAL=3500 bin/hubot -a telegram"
But there is such an error

[root@work-sys myhubot]# TELEGRAM_TOKEN=xxx:xxx TELEGRAM_INTERVAL=3500 bin/hubot -a telegram
audited 136 packages in 0.757s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[Sun Jul 12 2020 10:03:26 GMT+0800 (Hong Kong Standard Time)] INFO Telegram Adapter Bot 1370169281:AAEPoSUaBBTZNsd_R5azp0W8MPGH93f_wA4 Loaded...
[Sun Jul 12 2020 10:03:26 GMT+0800 (Hong Kong Standard Time)] INFO Telegram Adapter Started...
[Sun Jul 12 2020 10:03:26 GMT+0800 (Hong Kong Standard Time)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

Your hubot-scripts.json is empty, so you just need to remove it.
[Sun Jul 12 2020 10:03:26 GMT+0800 (Hong Kong Standard Time)] ERROR Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
  at Server.setupListenHandle [as _listen2] (net.js:1280:14)
  at listenInCluster (net.js:1328:12)
  at doListen (net.js:1461:7)
  at process._tickCallback (internal/process/next_tick.js:63:19)

[Sun Jul 12 2020 10:03:26 GMT+0800 (Hong Kong Standard Time)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Sun Jul 12 2020 10:03:27 GMT+0800 (Hong Kong Standard Time)] ERROR hubot-heroku-keepalive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s | grep web.url | cut -d= -f2)`
[Sun Jul 12 2020 10:03:27 GMT+0800 (Hong Kong Standard Time)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
[Sun Jul 12 2020 10:03:29 GMT+0800 (Hong Kong Standard Time)] INFO Telegram Bot Identified: devopstest
[Sun Jul 12 2020 10:03:29 GMT+0800 (Hong Kong Standard Time)] WARNING It is advised to use the same bot name as your Telegram Bot: bobdevopstest_bot
[Sun Jul 12 2020 10:03:29 GMT+0800 (Hong Kong Standard Time)] WARNING Having a different bot name can result in an inconsistent experience when using @mentions
[Sun Jul 12 2020 10:03:35 GMT+0800 (Hong Kong Standard Time)] ERROR Error: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
  at Function.TelegramBot.error (/data/myhubot/node_modules/telegrambot/lib/telegrambot.js:26:15)
  at Request._callback (/data/myhubot/node_modules/telegrambot/lib/telegrambot.js:47:66)
  at Request.self.callback (/data/myhubot/node_modules/request/request.js:185:22)
  at Request.emit (events.js:198:13)
  at Request.<anonymous> (/data/myhubot/node_modules/request/request.js:1154:10)
  at Request.emit (events.js:198:13)
  at IncomingMessage.<anonymous> (/data/myhubot/node_modules/request/request.js:1076:12)
  at Object.onceWrapper (events.js:286:20)
  at IncomingMessage.emit (events.js:203:15)
  at endReadableNT (_stream_readable.js:1145:12)
  at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lukefx** [comment]
Hi @okada8, yes that was an old problem... we have a branch open with a new implementation and this problem should not happen anymore. Could you try it please?

Install the next release with:

> npm I hubot-telegram@next

thank you
