### ISSUE TITLE
HTTP Error 409

### ISSUE THREAD

**Issue by routeaccess** [lukefx/hubot-telegram#9]
I had set up the adapter using the instructions provided in the Readme, but I've been getting HTTP Error 409. Telegram's [error handling documentation](https://core.telegram.org/api/errors) doesn't seem to have any explanation for this error code. 

Here is the console output : 
```
[Wed Jul 15 2015 11:37:36 GMT+0530 (IST)] ERROR Error: HTTP status 409 returned.
  at Function.TelegramBot.error (/Users/nevin/myhubot/node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:25:15)
  at Request._callback (/Users/nevin/myhubot/node_modules/hubot-telegram/node_modules/telegrambot/lib/telegrambot.js:45:62)
  at Request.self.callback (/Users/nevin/myhubot/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:197:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Users/nevin/myhubot/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:1050:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/Users/nevin/myhubot/node_modules/hubot-telegram/node_modules/telegrambot/node_modules/request/request.js:996:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

I also tested the same by deploying to Heroku (in case it's a network issue) but the logs show me the same output. [Here](http://www.chrisbrand.co.za/2015/06/11/using-telegram-with-hubot/)'s the instructions I followed.

**Comment by arcturial** [comment]
Hey, are you using a webhook to receive messages or polling for them?

**Comment by arcturial** [comment]
I published a new version of the underlying `telegrambot` library, it seems it's error handling wasn't passing through the actual content of the error. I replicated your issue and it seems it happens when you already have an active webhook. You can unset your webhook by calling the bot API like this:

`https://api.telegram.org/bot<token>/setWebhook?url=`

This will remove your active webhook and allow `getUpdates` to work as intended.

**Comment by routeaccess** [comment]
Thanks for the quick reply @arcturial 

I thought I didn't have webhooks enabled but I had played around with various API options and adapters earlier(was even writing one myself until I found yours) and that must have left a webhook dangling somewhere. I just revoked my earlier token and used a new one and the adapter works perfectly fine.

For anyone facing this issue - using a new token worked for me, or you may disable your webhook as mentioned above.
